version: '3.8'

networks:
  mcp-network:
    external: true

services:
  yt-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt-mcp-server
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PORT=8000
    networks:
      - mcp-network
